apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: nodejs-app
  namespace: asa-apps
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: nodejs-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: nodejs-app
    spec:
      containers:
      - image: caoxuyang/nodejstestapp:v1
        imagePullPolicy: Always
        name: nodejs-app
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 220m
            memory: 1Gi
        livenessProbe:
          failureThreshold: 10
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 1025
          timeoutSeconds: 5
        name: spring-boot-admin
        readinessProbe:
          failureThreshold: 6
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 1025
          timeoutSeconds: 5
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: nodejs-app
  namespace: asa-apps
  labels:
    app: nodejs-app
spec:
  ports:
    - port: 1025
      targetPort: 1025
  selector:
    app: nodejs-app
  type: ClusterIP
