apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
  name: sba-test-app
  namespace: <namespace>
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: sba-test-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
      labels:
        app: sba-test-app
    spec:
      containers:
      - image: <container-image>
        imagePullPolicy: Always
        name: sba-test-app
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 220m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
---
apiVersion: v1
kind: Service
metadata:
  name: sba-test-app
  namespace: <namespace>
  labels:
    app: sba-test-app
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sba-test-app
  type: ClusterIP
